version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - choco
  - cpack
  - ctest
  - gitmodule
  - Graphviz
  - jebbs
  - Seidensticker
ignoreWords:
  - Skjorta
  - mittelblau
import: []
