version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - autodoc
  - Ccache
  - choco
  - cpack
  - ctest
  - cyclomatic
  - fuzzer
  - GCOV
  - gitmodule
  - Graphviz
  - jebbs
  - LCOV
  - pmccabe
  - Seidensticker
  - sonarlint
  - struct
  - sysroot
  - Texinfo
ignoreWords:
  - Lplusplus
  - Skjorta
  - mittelblau
  - AFLplusplus
import: []
