version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Ccache
  - choco
  - cpack
  - ctest
  - fuzzer
  - GCOV
  - gitmodule
  - Graphviz
  - jebbs
  - LCOV
  - Seidensticker
  - sonarlint
  - struct
  - sysroot
ignoreWords:
  - Lplusplus
  - Skjorta
  - mittelblau
  - AFLplusplus
import: []
